---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "gha-runner-scale-set.serviceAccountName" . }}
  namespace: {{ include "gha-runner-scale-set.namespace" . }}
  labels:
    {{- include "gha-runner-scale-set.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "gha-runner-scale-set.serviceAccountName" . }}
  namespace: {{ include "gha-runner-scale-set.namespace" . }}
  labels:
    {{- include "gha-runner-scale-set.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "create", "delete"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["get", "create"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "list", "create", "delete"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "create", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "gha-runner-scale-set.serviceAccountName" . }}-worker

  namespace: {{ include "gha-runner-scale-set.namespace" . }}
  labels:
    {{- include "gha-runner-scale-set.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "gha-runner-scale-set.serviceAccountName" . }}
  namespace: {{ include "gha-runner-scale-set.namespace" . }}
  labels:
    {{- include "gha-runner-scale-set.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "gha-runner-scale-set.serviceAccountName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "gha-runner-scale-set.serviceAccountName" . }}
    namespace: {{ include "gha-runner-scale-set.namespace" . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "gha-runner-scale-set.serviceAccountName" . }}-worker

  namespace: {{ include "gha-runner-scale-set.namespace" . }}
  labels:
    {{- include "gha-runner-scale-set.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "gha-runner-scale-set.serviceAccountName" . }}-worker
subjects:
  - kind: ServiceAccount
    name: {{ .Values.applicationServiceAccount.name }}
    namespace: {{ include "gha-runner-scale-set.namespace" . }}
