apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gha-runner-scale-set.fullname" . }}
  namespace: {{ include "gha-runner-scale-set.namespace" . }}
  labels:
    {{- include "gha-runner-scale-set.labels" . | nindent 4 }}
data:
  default.yaml: |
    ---
    apiVersion: v1
    kind: PodTemplate
    metadata:
      name: {{ include "gha-runner-scale-set.fullname" . }}
      namespace: {{ include "gha-runner-scale-set.namespace" . }}
      labels:
        app: {{ include "gha-runner-scale-set.fullname" . }}
        app.kubernetes.io/part-of: gha-runner-scale-set
        sidecar.istio.io/inject: "false"
    spec:
      {{- if (.Values.checkVersion.enabled) }}
      initContainers:
        - name: check
          command: ["webhook"]
          image: "{{ .Values.checkVersion.image.repository }}:{{ .Values.checkVersion.image.tag }}"
          imagePullPolicy: {{ .Values.checkVersion.image.pullPolicy }}
          args:
            - "-check-version"
            - "-service"
            - "{{ .Values.checkVersion.service }}"
            - "-version"
            - "{{ .Values.checkVersion.version }}"
            - "-namespace"
            - "{{include "gha-runner-scale-set.namespace" .}}"
      {{- end }}
      securityContext:
        fsGroup: 123
      serviceAccountName: {{ .Values.applicationServiceAccount.name }}
