apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "gha-runner-scale-set.fullname" . }}
  namespace: {{ include "gha-runner-scale-set.namespace" . }}
  labels:
    {{- include "gha-runner-scale-set.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.externalSecret.storeName }}
    kind: {{ .Values.externalSecret.storeKind }}
  target:
    name: {{ include "gha-runner-scale-set.fullname" . }}
    creationPolicy: Owner
  data:
    - secretKey: github_app_id
      remoteRef:
        key: "{{ .Values.externalSecret.key }}"
        property: github_app_id
        conversionStrategy: Default
        decodingStrategy: None
    - secretKey: github_app_installation_id
      remoteRef:
        key: "{{ .Values.externalSecret.key }}"
        property: github_app_installation_id
        conversionStrategy: Default
        decodingStrategy: None
    - secretKey: github_app_private_key
      remoteRef:
        key: "{{ .Values.externalSecret.key }}"
        property: github_app_private_key
        conversionStrategy: Default
        decodingStrategy: Base64
