{{ if .Values.setIstioPeerAuthentication -}}
kind: PeerAuthentication
apiVersion: security.istio.io/v1beta1
metadata:
  name: {{ include "gha-runner-scale-set.fullname" . }}
  namespace: {{ include "gha-runner-scale-set.namespace" . }}
  labels:
    {{- include "gha-runner-scale-set.labels" . | nindent 4 }}
spec:
  mtls:
    mode: PERMISSIVE
  selector:
    labels:
      app.kubernetes.io/part-of: gha-runner-scale-set
{{- end}}
