{{- range $key, $value := $.Values.stores}}
{{- range $index, $secret := $value.secrets}}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{$secret.destName}}
spec:
  refreshInterval: {{$secret.refreshInterval | default "1h"}}
  secretStoreRef:
    name: {{$key}}
    kind: SecretStore
  target:
    name: {{$secret.destName}}
  data:
    - remoteRef:
        key: {{$secret.sourcePath}}
        property: {{$secret.sourceKey}}
      secretKey: {{$secret.destKey}}
---
{{- end}}
{{- end}}
