{{- range $key, $value := $.Values.stores}}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "secrets-{{$key}}"
  labels:
    {{- include "secretstores.labels" $ | nindent 4 }}
spec:
  refreshInterval: {{$value.refreshInterval | default "1h" | quote}}
  secretStoreRef:
    name: {{$key | quote}}
    kind: "SecretStore"
  target:
    name: "secrets-{{$key}}"
  {{- if $value.secrets}}
  data:
    {{- range $index, $secret := $value.secrets}}
    - remoteRef:
        key: {{$secret.sourcePath | quote}}
        property: {{$secret.sourceKey | quote}}
      secretKey: {{$secret.destKey | default $secret.sourceKey | quote}}
    {{- end}}
  {{- else}}
  dataFrom:
    {{- if eq $value.type "aws"}}
    - find:
        path: "{{$.Values.global.env}}/{{include "secretstores.fullname" $}}"
        name:
          regexp: ".*"
      rewrite:
        - regexp:
          source: "{{$.Values.global.env}}/(.*)"
          target: "$1"
    - find:
        path: "{{$.Values.global.env}}/shared"
        name:
          regexp: ".*"
      rewrite:
        - regexp:
          source: "{{$.Values.global.env}}/(.*)"
          target: "$1"
    - find:
        path: "shared"
        name:
          regexp: ".*"
    {{- else}}
    - find:
        path: {{include "secretstores.fullname" $ | quote }}
        name:
          regexp: ".*"
    {{- end}}
    {{- with $value.additionalSecretsPaths}}
    {{- range .}}
    - find:
        path: {{. | quote}}
        name:
          regexp: ".*"
    {{- end}}
    {{- end}}
  {{- end}}
---
{{- end}}
