{{- range $key, $value := $.Values.stores}}
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{$key}}
  namespace: {{$.Values.namespace}}
  {{- with $.Values.annotations}}
  annotations:
    {{- toYaml . | nindent 4}}
  {{- end}}
spec:
  # Provider field contains the configuration to access the provider which
  # contains the secret.
  # Exactly one provider must be configured.
  provider:
    {{- if eq $value.type "aws"}}
    # AWS Secrets Manager
    # AWS configures this store to sync secrets using AWS Secret Manager provider
    aws:
      service: SecretsManager
      # Role is a Role ARN which the SecretManager provider will assume
      role: {{$value.iamRole}}
      # AWS Region to be used for the provider
      region: {{$value.region}}
    {{- else if eq $value.type "vault"}}
    # Vault - {{$value.path}}/
    # Sync secrets with the {{$value.path}}/ mount in Vault
    vault:
      server: {{$value.server}}
      # Path is the mount path of the Vault KV backend endpoint
      path: {{$value.path}}
      auth:
        # Kubernetes auth: https://www.vaultproject.io/docs/auth/kubernetes
        kubernetes:
          mountPath: "kubernetes"
          role: {{$.Values.serviceName}}
          serviceAccountRef:
            name: {{$.Values.serviceName}}
            namespace: {{$.Values.namespace}}
    {{- end }}
---
{{- end }}
