{{- if .Values.enabled }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{include "gha-runner-deployment.fullname" .}}
  namespace: {{include "gha-runner-deployment.namespace" .}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{include "gha-runner-deployment.fullname" .}}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccount.name }}
    namespace: {{include "gha-runner-deployment.namespace" .}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: check-version
  namespace: {{include "gha-runner-deployment.namespace" .}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: check-version
subjects:
  - kind: ServiceAccount
    name: {{ .Values.applicationServiceAccount.name }}
    namespace: {{include "gha-runner-deployment.namespace" .}}
{{- end }}
