{{- if .Values.enabled }}
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: {{ include "gha-runner-deployment.fullname" . }}
  namespace: {{ include "gha-runner-deployment.namespace" . }}
  labels:
    {{- include "gha-runner-deployment.labels" . | nindent 4}}
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    {{- with .Values.runnerDeployment.metadata }}
    metadata:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.runnerDeployment.spec }}
    spec:
        {{- toYaml . | nindent 6 }}
    {{- end }}
{{- end }}
