{{- if and .Values.serviceAccount.create .Values.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: {{include "gha-runner-deployment.namespace" .}}
  {{- with .Values.serviceAccount.annotations}}
  annotations:
    {{ toYaml . | indent 4 }}
  {{- end }}
{{- end }}
