---
apiVersion: batch/v1
kind: Job
metadata:
  namespace: {{.Values.namespace}}
  generateName: {{.Values.app.name}}-gh-status-in-progress-
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
    argocd.argoproj.io/sync-wave: "1"
spec:
  template:
    metadata:
      labels:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
        - name: update-gh-status-in-progress
          image: "{{.Values.deployTrackerImage.account}}.dkr.ecr.{{.Values.deployTrackerImage.repoRegion}}.amazonaws.com/{{.Values.deployTrackerImage.repoName}}:{{.Values.deployTrackerImage.tag}}"  # yamllint disable-line rule:line-length
          env:
            - name: GITHUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: argocd-external-secret-github
                  key: github-token
            - name: AWS_DEFAULT_REGION
              value: {{.Values.deployTrackerImage.repoRegion}}
          args: [ "status", "--repo", "{{.Values.app.repoName}}", "--ref", "{{.Values.app.tag}}", "--state", "in_progress", "--environment", "{{.Values.env}}"]
      restartPolicy: Never
  backoffLimit: 0
